# Generated by Django 4.1.3 on 2022-11-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
